<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPEbzVhY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPEbzVhY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPEbzVhY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPEbzVhY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPEbzVhY\App_KernelDevDebugContainer([
    'container.build_hash' => 'PEbzVhY',
    'container.build_id' => '7336b930',
    'container.build_time' => 1626222929,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPEbzVhY');
