<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxqrsfv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxqrsfv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxqrsfv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxqrsfv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxqrsfv\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xxqrsfv',
    'container.build_id' => '23d00f18',
    'container.build_time' => 1626216383,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxqrsfv');
