<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6juB6op\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6juB6op/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6juB6op.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6juB6op\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6juB6op\App_KernelDevDebugContainer([
    'container.build_hash' => '6juB6op',
    'container.build_id' => '4be05cc0',
    'container.build_time' => 1626225762,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6juB6op');
